module Eagle
  # Base class for input and window events, delivered to `App#input` and `Node#input`.
  #
  # Use events when you care that something happened: a key went down, a button was
  # clicked, the window resized. For "is this key held right now?", ask `Input` instead.
  #
  # Nodes receive events deepest-first, in reverse order of addition, so the thing
  # drawn on top gets the first chance. Set `handled = true` to stop the event from
  # reaching anything else.
  #
  # ```
  # class Menu < Node2D
  #   def input(event : Event) : Nil
  #     case event
  #     when KeyEvent
  #       if event.pressed? && event.key.escape?
  #         visible = !visible?
  #         event.handled = true
  #       end
  #     when MouseButtonEvent
  #       puts "click at #{event.position}" if event.pressed?
  #     end
  #   end
  # end
  # ```
  abstract class Event
    # Set to true in a handler to stop the event from reaching later nodes.
    property? handled = false
  end

  # A keyboard key went down or up. Key repeat sends more presses with `repeat?` set.
  # For typed text, use `TextEvent`, which handles keyboard layouts and dead keys.
  class KeyEvent < Event
    # The key, by physical position.
    getter key : Key
    # True for a press, false for a release.
    getter? pressed : Bool
    # True for presses generated by holding the key down.
    getter? repeat : Bool
    # Modifier keys held at the time.
    getter mods : KeyMod
    # Creates a key event, for `Eagle.inject` and tests.
    def initialize(@key, @pressed, @repeat = false, @mods = KeyMod::None); end
    # True when the key was released.
    def released? : Bool; !@pressed; end
  end

  # Text the player typed, already composed by the OS (accents, CJK input and so on).
  # Enable it with `Input.text_input = true`; `TextInput` controls do this for you.
  class TextEvent < Event
    # The typed text, which can be several characters.
    getter text : String
    # Creates a text event.
    def initialize(@text); end
  end

  # A mouse button went down or up. `position` is in window coordinates, and `clicks` is
  # 2 for a double-click.
  class MouseButtonEvent < Event
    # Which mouse button.
    getter button : MouseButton
    # True for a press, false for a release.
    getter? pressed : Bool
    # Mouse position in window coordinates.
    getter position : Vec2
    # 1 for a single click, 2 for a double-click.
    getter clicks : Int32
    # True when this click was synthesized from a touch. See `Touch.emulate_mouse=`.
    property? from_touch = false
    # Creates a mouse button event.
    def initialize(@button, @pressed, @position, @clicks = 1); end
    # True when the button was released.
    def released? : Bool; !@pressed; end
  end

  # The mouse moved. `delta` is the movement since the last event, which still works
  # when `Window.relative_mouse=` has locked the cursor.
  class MouseMotionEvent < Event
    # Mouse position in window coordinates.
    getter position : Vec2
    # Movement since the last motion event.
    getter delta : Vec2
    # True when this motion was synthesized from a touch. See `Touch.emulate_mouse=`.
    property? from_touch = false
    # Creates a mouse motion event.
    def initialize(@position, @delta); end
  end

  # The wheel or trackpad scrolled. `delta.y` is positive when scrolling up.
  class MouseWheelEvent < Event
    # Scroll amount. Positive y scrolls up.
    getter delta : Vec2
    # Mouse position in window coordinates.
    getter position : Vec2
    # Creates a mouse wheel event.
    def initialize(@delta, @position); end
  end

  # What a finger did in a `TouchEvent`.
  enum TouchPhase
    # The finger touched the screen.
    Began
    # The finger moved.
    Moved
    # The finger lifted.
    Ended
    # The system took the touch away (a call, a swipe from the screen edge). Undo, don't commit.
    Cancelled
  end

  # A finger touched, moved on, or left the screen. Every finger has an `id` that stays the
  # same from `Began` to `Ended` or `Cancelled`, so you can follow several fingers at once.
  #
  # Positions are in window coordinates, the same space as the mouse. Set `handled = true` to
  # claim the touch; an unhandled touch is also turned into mouse events while
  # `Touch.emulate_mouse=` is on. For polling instead of events, see `Touch`.
  #
  # ```
  # class Pad < Node2D
  #   def input(event : Event) : Nil
  #     if event.is_a?(TouchEvent) && event.began?
  #       puts "finger #{event.id} down at #{event.position}"
  #       event.handled = true
  #     end
  #   end
  # end
  # ```
  class TouchEvent < Event
    # Stable finger id, from 0.
    getter id : Int32
    # What the finger did.
    getter phase : TouchPhase
    # Finger position in window coordinates.
    getter position : Vec2
    # How hard the finger presses, from 0 to 1. Devices without pressure report 1.
    getter pressure : Float32
    # Movement since this finger's previous event. Filled in by `Input` before delivery.
    property delta : Vec2 = Vec2::ZERO
    # Creates a touch event, for `Eagle.inject` and tests.
    def initialize(@id, @phase, @position, @pressure = 1_f32); end
    # True when the finger just touched down.
    def began? : Bool; @phase.began?; end
    # True when the finger moved.
    def moved? : Bool; @phase.moved?; end
    # True when the finger lifted.
    def ended? : Bool; @phase.ended?; end
    # True when the system cancelled the touch.
    def cancelled? : Bool; @phase.cancelled?; end
  end

  # Where a finger is in a drag, for `TouchDragEvent`.
  enum TouchDragKind
    # The finger moved past `Touch.drag_threshold`.
    Started
    # The finger moved while dragging.
    Moved
    # The finger lifted, or the touch was cancelled.
    Ended
  end

  # A finger has moved far enough to count as a drag, not a tap. Started fires once the finger
  # passes `Touch.drag_threshold` pixels from where it landed, Moved fires on each move after
  # that and Ended when it lifts. Delivered to `App#input` and `Node#input` like any event.
  #
  # ```
  # class Card < Node2D
  #   def input(event : Event) : Nil
  #     if event.is_a?(TouchDragEvent) && event.moved?
  #       self.position += event.delta
  #     end
  #   end
  # end
  # ```
  class TouchDragEvent < Event
    # The finger's id.
    getter id : Int32
    # Started, Moved or Ended.
    getter kind : TouchDragKind
    # Current finger position.
    getter position : Vec2
    # Where the finger first touched down.
    getter start : Vec2
    # Movement since the previous drag event. On Started it is the total travel so far.
    getter delta : Vec2
    # True for an Ended event caused by a cancelled touch.
    getter? cancelled : Bool
    # Creates a drag event.
    def initialize(@id, @kind, @position, @start, @delta, @cancelled = false); end
    # True for the first drag event.
    def started? : Bool; @kind.started?; end
    # True for drag movement.
    def moved? : Bool; @kind.moved?; end
    # True for the last drag event.
    def ended? : Bool; @kind.ended?; end
    # Total travel from where the finger landed.
    def total : Vec2; @position - @start; end
  end

  # What happened to the window in a `WindowEvent`.
  enum WindowEventKind
    # The window changed size.
    Resized
    # The window gained keyboard focus.
    FocusGained
    # The window lost keyboard focus.
    FocusLost
    # The mouse moved into the window.
    MouseEnter
    # The mouse left the window.
    MouseLeave
    # The window was minimized.
    Minimized
    # The window was restored from minimized or maximized.
    Restored
    # The player asked to close the window.
    Close
  end

  # The window was resized, gained or lost focus, was minimized or restored, or the mouse
  # entered or left it. `App#resize` and `Node#resized` already cover resizing.
  class WindowEvent < Event
    # What happened to the window.
    getter kind : WindowEventKind
    # The window size, for `Resized` events.
    getter size : Vec2
    # Creates a window event.
    def initialize(@kind, @size = Vec2::ZERO); end
  end

  # A gamepad button went down or up. `gamepad` is the controller's id.
  class GamepadButtonEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # Which button.
    getter button : GamepadButton
    # True for a press, false for a release.
    getter? pressed : Bool
    # Creates a gamepad button event.
    def initialize(@gamepad, @button, @pressed); end
  end

  # A gamepad stick or trigger moved, with `value` from -1 to 1 (0 to 1 for triggers).
  class GamepadAxisEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # Which stick or trigger axis.
    getter axis : GamepadAxis
    # The axis value: -1 to 1 for sticks, 0 to 1 for triggers.
    getter value : Float32
    # Creates a gamepad axis event.
    def initialize(@gamepad, @axis, @value); end
  end

  # A gamepad was plugged in or unplugged.
  class GamepadConnectionEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # True when plugged in, false when unplugged.
    getter? connected : Bool
    # Creates a gamepad connection event.
    def initialize(@gamepad, @connected); end
  end

  # A file was dragged onto the window. `path` is its full path, for level editors and viewers.
  class FileDropEvent < Event
    # Full path of the dropped file.
    getter path : String
    # Creates a file drop event.
    def initialize(@path); end
  end

  # The player asked to close the window. `App#quit?` decides whether to actually quit.
  class QuitEvent < Event
    # Creates a quit event.
    def initialize; end
  end
end
