module Eagle
  # Base class for input and window events, delivered to `App#input` and `Node#input`.
  #
  # Use events when you care that something happened: a key went down, a button was
  # clicked, the window resized. For "is this key held right now?", ask `Input` instead.
  #
  # Nodes receive events deepest-first, in reverse order of addition, so the thing
  # drawn on top gets the first chance. Set `handled = true` to stop the event from
  # reaching anything else.
  #
  # ```
  # class Menu < Node2D
  #   def input(event : Event) : Nil
  #     case event
  #     when KeyEvent
  #       if event.pressed? && event.key.escape?
  #         visible = !visible?
  #         event.handled = true
  #       end
  #     when MouseButtonEvent
  #       puts "click at #{event.position}" if event.pressed?
  #     end
  #   end
  # end
  # ```
  abstract class Event
    # Set to true in a handler to stop the event from reaching later nodes.
    property? handled = false
  end

  # A keyboard key went down or up. Key repeat sends more presses with `repeat?` set.
  # For typed text, use `TextEvent`, which handles keyboard layouts and dead keys.
  class KeyEvent < Event
    # The key, by physical position.
    getter key : Key
    # True for a press, false for a release.
    getter? pressed : Bool
    # True for presses generated by holding the key down.
    getter? repeat : Bool
    # Modifier keys held at the time.
    getter mods : KeyMod
    # Creates a key event, for `Eagle.inject` and tests.
    def initialize(@key, @pressed, @repeat = false, @mods = KeyMod::None); end
    # True when the key was released.
    def released? : Bool; !@pressed; end
  end

  # Text the player typed, already composed by the OS (accents, CJK input and so on).
  # Enable it with `Input.text_input = true`; `TextInput` controls do this for you.
  class TextEvent < Event
    # The typed text, which can be several characters.
    getter text : String
    # Creates a text event.
    def initialize(@text); end
  end

  # A mouse button went down or up. `position` is in window coordinates, and `clicks` is
  # 2 for a double-click.
  class MouseButtonEvent < Event
    # Which mouse button.
    getter button : MouseButton
    # True for a press, false for a release.
    getter? pressed : Bool
    # Mouse position in window coordinates.
    getter position : Vec2
    # 1 for a single click, 2 for a double-click.
    getter clicks : Int32
    # Creates a mouse button event.
    def initialize(@button, @pressed, @position, @clicks = 1); end
    # True when the button was released.
    def released? : Bool; !@pressed; end
  end

  # The mouse moved. `delta` is the movement since the last event, which still works
  # when `Window.relative_mouse=` has locked the cursor.
  class MouseMotionEvent < Event
    # Mouse position in window coordinates.
    getter position : Vec2
    # Movement since the last motion event.
    getter delta : Vec2
    # Creates a mouse motion event.
    def initialize(@position, @delta); end
  end

  # The wheel or trackpad scrolled. `delta.y` is positive when scrolling up.
  class MouseWheelEvent < Event
    # Scroll amount. Positive y scrolls up.
    getter delta : Vec2
    # Mouse position in window coordinates.
    getter position : Vec2
    # Creates a mouse wheel event.
    def initialize(@delta, @position); end
  end

  # What happened to the window in a `WindowEvent`.
  enum WindowEventKind
    # The window changed size.
    Resized
    # The window gained keyboard focus.
    FocusGained
    # The window lost keyboard focus.
    FocusLost
    # The mouse moved into the window.
    MouseEnter
    # The mouse left the window.
    MouseLeave
    # The window was minimized.
    Minimized
    # The window was restored from minimized or maximized.
    Restored
    # The player asked to close the window.
    Close
  end

  # The window was resized, gained or lost focus, was minimized or restored, or the mouse
  # entered or left it. `App#resize` and `Node#resized` already cover resizing.
  class WindowEvent < Event
    # What happened to the window.
    getter kind : WindowEventKind
    # The window size, for `Resized` events.
    getter size : Vec2
    # Creates a window event.
    def initialize(@kind, @size = Vec2::ZERO); end
  end

  # A gamepad button went down or up. `gamepad` is the controller's id.
  class GamepadButtonEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # Which button.
    getter button : GamepadButton
    # True for a press, false for a release.
    getter? pressed : Bool
    # Creates a gamepad button event.
    def initialize(@gamepad, @button, @pressed); end
  end

  # A gamepad stick or trigger moved, with `value` from -1 to 1 (0 to 1 for triggers).
  class GamepadAxisEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # Which stick or trigger axis.
    getter axis : GamepadAxis
    # The axis value: -1 to 1 for sticks, 0 to 1 for triggers.
    getter value : Float32
    # Creates a gamepad axis event.
    def initialize(@gamepad, @axis, @value); end
  end

  # A gamepad was plugged in or unplugged.
  class GamepadConnectionEvent < Event
    # The controller's id.
    getter gamepad : Int32
    # True when plugged in, false when unplugged.
    getter? connected : Bool
    # Creates a gamepad connection event.
    def initialize(@gamepad, @connected); end
  end

  # A file was dragged onto the window. `path` is its full path, for level editors and viewers.
  class FileDropEvent < Event
    # Full path of the dropped file.
    getter path : String
    # Creates a file drop event.
    def initialize(@path); end
  end

  # The player asked to close the window. `App#quit?` decides whether to actually quit.
  class QuitEvent < Event
    # Creates a quit event.
    def initialize; end
  end
end
