require "./eagle/version"
require "./eagle/math/math"
require "./eagle/core/error"
require "./eagle/core/log"
require "./eagle/core/clock"
require "./eagle/core/signal"
require "./eagle/core/events"
require "./eagle/input/keys"
require "./eagle/input/input"
require "./eagle/platform/wasm_shim"
require "./eagle/platform/base"
{% if flag?(:wasm32) %}
  require "./eagle/platform/web"
{% else %}
  require "./eagle/platform/sdl"
{% end %}
require "./eagle/gpu/device"
require "./eagle/gpu/gl33"
require "./eagle/assets/image"
require "./eagle/assets/codecs/codecs"
require "./eagle/assets/assets"
require "./eagle/graphics/texture"
require "./eagle/graphics/shader"
require "./eagle/graphics/canvas"
require "./eagle/graphics/font"
require "./eagle/graphics/truetype"
require "./eagle/graphics/graphics"
require "./eagle/graphics3d/mesh"
require "./eagle/graphics3d/material"
require "./eagle/graphics3d/renderer3d"
require "./eagle/audio/audio"
require "./eagle/physics/physics2d"
require "./eagle/physics/physics3d"
require "./eagle/core/tween"
require "./eagle/core/script"
require "./eagle/core/node"
require "./eagle/core/scene_tree"
require "./eagle/core/window"
require "./eagle/nodes/nodes"
require "./eagle/ui/ui"
require "./eagle/core/engine"

# Eagle — a Crystal-native 2D/3D game engine.
module Eagle
end
